#!/bin/bash
# inpath--Verifies that a specified program is either valid as is
# or can be found in the PATH directory list
in_path()
{
# Given a command and the PATH, tries to find the command. Returns 0 if
# found and executable; 1 if not. Note that this temporarily modifies
# the IFS (internal field separator) but restores it upon completion.
cmd=$1 ourpath=$2 result=1
if which $cmd ; then
    #echo the command $cmd is somewhere
    basdir=$(dirname $(which $cmd))
    if [[ :$PATH: == *:"$basdir":* ]] ; then
    
    #if  echo $PATH | grep $basdir ; then
    #echo we are in the path!!
    result=0
    fi
fi
return $result
}
checkForCmdInPath()
{
var=$1
in_path $var "$PATH"
res=$?
if [[ $res = 0 ]] ; then
    if  [[ ! -x $(which var) ]] ; then
        res=2
    fi
return $res
fi


}

# standalone part
if [ $# -ne 1 ] ; then
    echo "Usage: $0 command" >&2
    exit 1
fi

checkForCmdInPath "$1"
    case $? in
        0 ) echo "$1 found in PATH" ;;
        1 ) echo "$1 not found or not executable" ;;
        2 ) echo "$1 not found in PATH" ;;
    esac

exit 0

